### ISSUE TITLE
getting server.jsx: Unexpected token (40:8)

### ISSUE THREAD

**Issue by thehashrocket** [bananaoomarang/isomorphic-redux#45]
When trying to run the app, I'm hitting the following error:

<img width="1036" alt="terminal_ _-bash_ _147x38_and_gradebook" src="https://cloud.githubusercontent.com/assets/342353/12433508/b2be465c-bebe-11e5-8ac5-1e26c42d6e12.png">

I cloned the app, ran `npm install`, and then `npm run dev` and immediately hit it. :/

Any idea what's going on?

**Comment by bananaoomarang** [comment]
This is strange, I can't reproduce this here after a fresh delete global modules and `npm install`.

It looks like babel is choking on Jsx, but I'm not sure why that would be, sine we're running the same configurations with the same modules.

If anyone else can reproduce that might help, but otherwise my best (if a little lame&hellip;) advice is to do a `git reset --hard && git pull && rm -rf node_modules && npm i`.

**Comment by melervand** [comment]
maybe you've forgot to include .babelrc and .eslintrc ?

**Comment by wahengchang** [comment]
same, and I could not find a way to fix it
