### ISSUE TITLE
Feature request: Versioning

### ISSUE THREAD

**Issue by nhsiehgit** [bananaoomarang/isomorphic-redux#46]
Hey Thanks for the great tutorial!

I know there've been tons of breaking changes with all these libraries and everything changes so quickly. As of now, i noticed that your tutorial and the github repo are out of sync

I was wondering, (and maybe its too late) - but would you be able to tag different versions of the repo? ie. just noticed that the tutorial was written for babel 5.x.x, however this repo's now been updated to 6.x.x

I was going through the tut and noticing things were breaking so came to this repo to try and copy files over, but then noticed it was completely off haha.

Thanks!

**Comment by bananaoomarang** [comment]
Yeah, I am so sorry about this. Have been super disorganized about it!

It’s not perfect, because the tutorial and repo were not always updated so in sync, but I just tagged something which [looks a lot more like the tutorial](https://github.com/bananaoomarang/isomorphic-redux/tree/tutorial). I don't think there are any huge differences, though if there are let me know and I'll try to reconcile them more.

Hope this is some help!

**Comment by nhsiehgit** [comment]
cool thanks!

In particular one thing that caught me off guard was how webpack was now configured. Noticed it had now been split off into multiple files which was a bit confusing and took some searching to get through. I suppose most of my questions were regarding the build tool setup haha

**Comment by bananaoomarang** [comment]
Yeah, I can see that'd be annoying. If I get time at the weekend I'll update the tutorial to have a `prod.config.js` or rewrite a little git history.
