### ISSUE TITLE
Error importing router. Why repo works?

### ISSUE THREAD

**Issue by felixsanz** [bananaoomarang/isomorphic-redux#55]
on line 5 -> `import routes                    from 'routes';`

Why it does even works? There is no routes.js/jsx or routes/ folder. It makes no sense :confused:

**Comment by Dattaya** [comment]
Importing this way works due to this line in the [webpack config](https://github.com/bananaoomarang/isomorphic-redux/blob/master/webpack.prod.config.js#L9): `modulesDirectories: ['node_modules', 'shared'],`
It will search not only `node_modules` but also `shared` folder where `routes.jsx` is currently located.

**Comment by felixsanz** [comment]
thanks!
