### ISSUE TITLE
React-router v0.13.3

### ISSUE THREAD

**Issue by Azaeres** [bananaoomarang/isomorphic-redux#7]
I was wondering why the `onLeave` handlers weren't working for me; then I noticed that we're using different versions.  I'm using 'react-router' v0.13.3, which has removed support for the `onLeave` handler.  I figured they probably recommend an alternative approach, but I haven't had much luck in determining what that would be.

Do you happen to know how we can fetch a component's needed data on a page transition (as you have done here) with the latest `react-router`?  Thanks!

**Comment by bananaoomarang** [comment]
I actually built the tutorial using `react-router`'s `1.0.0-beta`, which is newer than npm's 'latest'. This is because a lot has changed and 1.0.0 should be released officially very soon now. I must admit I am also confused (there has been a lot of churn!) but as of now `onLeave` seems to be working.

It's also not a perfect solution (when working with nested routes, since transitioning from parent to child does not count as 'leave') so I have been meaning to look into something more robust. If I figure out something better I may well update the blog to reflect that, but for now `onLeave` seems the best bet. You can get the beta by using the `package.json` here or installing explicitly (`npm i --save react-router@1.0.0-beta3`) until it gets released officially.

**Comment by Azaeres** [comment]
Ah, I see!  Thanks.

**Comment by Azaeres** [comment]
With the release of `react-router` `1.0.0-rc3` a couple weeks ago, I was wondering if you had any idea of how we are now expected to attach a handler to a page transition (for the dynamic fetching of data on the client).  Any clue I can follow?

**Comment by Azaeres** [comment]
I figured it out.  When the client transitions to a page, the `onEnter` handler for a Route is given a `nextState` object that has all the info I was looking for:  the list of routes (and their components) that were matched, params, and location.  Just calling `fetchComponentData` with that info updates the Redux state, and it appears to be working for me.
